### ISSUE TITLE
Is zcertificate going to be updated to a more modern version of zlint?

### ISSUE THREAD

**Issue by pjsg** [zmap/zcertificate#15]
It seems that the current version of zlint being used is from 2019 -- which seems like a lifetime ago. Any plans to update to a more recent version?

**Comment by cpu** [comment]
It should be fairly straightforward to drop in a newer version. If nobody else does over the next few days I'll take a crack at it.

As a follow-up it would be nice to add command line options for including/excluding lint categories using the newer ZLint 2.x+ API but I'm not sure I'll have time to get to that.

**Comment by cpu** [comment]
:wave: @pjsg - Thanks for opening this issue to prop an update. Sine #17 ZCertificate is using v2.2.1, the latest tagged release.
