### ISSUE TITLE
ZCertificate cannot parse the extension "authority key identifier".

### ISSUE THREAD

**Issue by GOODPWDCETCSZ** [zmap/zcertificate#23]
Env: Ubuntu x64

Go version: 1.13, 1.15

Cmd: `./zcertificate seed-77s38-921c17.pem`

Expected result: to show duplicate the extension "authority key identifier".

Actual result: 

```
"extensions":{"key_usage":{"certificate_sign":true,"value":32},"basic_constraints":{"is_ca":false},"subject_key_id":"bc93a7c14d51a1b11e5dc9c191eadb5b53d5bc58"},"unknown_extensions":[{"id":"2.16.840.1.113730.1.13","critical":true,"value":"Fh1oZXJlIGlzIHRoZSBuc0NvbW1lbnQgY29udGVudA=="}]
```

As seankhliao replied in https://github.com/golang/go/issues/43868, "this appears to be an issue with zcertificate".

[seed-77s38-921c17.zip](https://github.com/zmap/zcertificate/files/5861406/seed-77s38-921c17.zip)

**Comment by cpu** [comment]
Hi @GOODPWDCETCSZ,

Collecting certificate extensions into a JSON representation is handled in [github.com/zmap/zcrypto](https://github.com/zmap/zcrypto) by [the `jsonifyExtensions` function](https://github.com/zmap/zcrypto/blob/9cf5beac6d9132f5bd3571ed8a5fc436db0364eb/x509/extensions.go#L727-L818) from the forked `x509` package. As you've intuited from the output this process doesn't include duplicates in the resulting JSON though they are present in the parsed certificate.

Unfortunately I'm afraid I have to bounce your issue to another repo yet again and close this one. I think if you want a way to see duplicate extensions in the JSON output it should be a feature request made on ZCrypto. I don't know what your use-case is so I'll leave that one to you to file if you don't mind.

I also noticed there's an existing ZLint lint for this case, `e_ext_duplicate_extension`, that is correctly returning an error for this certificate:
```
> zcertificate ./issue.23/seed-77s38-921c17.pem | jq .zlint.lints.e_ext_duplicate_extension
INFO[0000] reading from ./issue.23/seed-77s38-921c17.pem
INFO[0000] writing to stdout
{
  "result": "error"
}
```

I think it would be nicer if that error result also included a `details` message that indicated the OID of the duplicated extension(s). I filed [this ZLint issue](https://github.com/zmap/zlint/issues/549) to address that improvement.

Thanks for filing an issue - apologies for bouncing you over to ZCrypto :-)
