### ISSUE TITLE
Build error on zcertificate/cmd/zcertificate/main.go

### ISSUE THREAD

**Issue by BBerastegui** [zmap/zcertificate#8]
Hey, just by running `go get github.com/zmap/zcertificate/cmd/zcertificate` on a clean golang env throws this error:

```
# github.com/zmap/zcertificate/cmd/zcertificate
src/github.com/zmap/zcertificate/cmd/zcertificate/main.go:75:39: cannot use parsed (type *"github.com/zmap/zcrypto/x509".Certificate) as type *"github.com/zmap/zlint/vendor/github.com/zmap/zcrypto/x509".Certificate in argument to zlint.LintCertificate
```

Sorry that I can't be of any help, I really have no idea of what's happening here and I think I'm missing something super obvious :)

Edit: `go version go1.11.4 linux/amd64`

**Comment by BBerastegui** [comment]
Okay, now I get it more or less :)

`Gopkg.toml`:

```
[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.4.1"

[[constraint]]
  branch = "master"
  name = "github.com/zmap/zcrypto"

[[constraint]]
  branch = "master"
  name = "github.com/zmap/zlint"

[prune]
  go-tests = true
  unused-packages = true
```

I will leave for you guys to decide how do you want to add the dependencies (Gopkg.toml and Gopkg.lock or by any other means).

**Comment by cpu** [comment]
I believe this issue is stale with the current state of master. The dependencies are pinned via go.mod.
